CREATE TABLE [dbo].[Tags]
(
	[TagId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Tag] NVARCHAR(50) NOT NULL, 
    [TodoId] UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (TodoId) REFERENCES Todos([TodoId]) ON DELETE CASCADE
)
